// AUTO-GENERATED by scripts/gen-schema.js. Do not hand-edit; re-run the generator instead.
export interface EntityColumn {
  column: string;
  jsonProp: string;
  type: string;
}

export interface EntityDef {
  name: string;
  table: string;
  columns: EntityColumn[];
}

export const ENTITY_REGISTRY: Record<string, EntityDef> = {
  ArtistBooking: {
  "name": "ArtistBooking",
  "table": "artist_bookings",
  "columns": [
    {
      "column": "artist_id",
      "jsonProp": "artist_id",
      "type": "text"
    },
    {
      "column": "artist_name",
      "jsonProp": "artist_name",
      "type": "text"
    },
    {
      "column": "requester_name",
      "jsonProp": "requester_name",
      "type": "text"
    },
    {
      "column": "requester_email",
      "jsonProp": "requester_email",
      "type": "text"
    },
    {
      "column": "requester_phone",
      "jsonProp": "requester_phone",
      "type": "text"
    },
    {
      "column": "booking_type",
      "jsonProp": "booking_type",
      "type": "text"
    },
    {
      "column": "event_date",
      "jsonProp": "event_date",
      "type": "date"
    },
    {
      "column": "venue",
      "jsonProp": "venue",
      "type": "text"
    },
    {
      "column": "budget",
      "jsonProp": "budget",
      "type": "numeric"
    },
    {
      "column": "message",
      "jsonProp": "message",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    }
  ]
},
  ArtistProfile: {
  "name": "ArtistProfile",
  "table": "artist_profiles",
  "columns": [
    {
      "column": "name",
      "jsonProp": "name",
      "type": "text"
    },
    {
      "column": "stage_name",
      "jsonProp": "stage_name",
      "type": "text"
    },
    {
      "column": "bio",
      "jsonProp": "bio",
      "type": "text"
    },
    {
      "column": "genre",
      "jsonProp": "genre",
      "type": "text"
    },
    {
      "column": "country",
      "jsonProp": "country",
      "type": "text"
    },
    {
      "column": "city",
      "jsonProp": "city",
      "type": "text"
    },
    {
      "column": "location",
      "jsonProp": "location",
      "type": "text"
    },
    {
      "column": "manager_name",
      "jsonProp": "manager_name",
      "type": "text"
    },
    {
      "column": "booking_email",
      "jsonProp": "booking_email",
      "type": "text"
    },
    {
      "column": "phone",
      "jsonProp": "phone",
      "type": "text"
    },
    {
      "column": "whatsapp",
      "jsonProp": "whatsapp",
      "type": "text"
    },
    {
      "column": "booking_fee",
      "jsonProp": "booking_fee",
      "type": "numeric"
    },
    {
      "column": "performance_fee",
      "jsonProp": "performance_fee",
      "type": "numeric"
    },
    {
      "column": "feature_price",
      "jsonProp": "feature_price",
      "type": "numeric"
    },
    {
      "column": "collaboration_price",
      "jsonProp": "collaboration_price",
      "type": "numeric"
    },
    {
      "column": "songwriting_price",
      "jsonProp": "songwriting_price",
      "type": "numeric"
    },
    {
      "column": "studio_session_price",
      "jsonProp": "studio_session_price",
      "type": "numeric"
    },
    {
      "column": "music_video_price",
      "jsonProp": "music_video_price",
      "type": "numeric"
    },
    {
      "column": "services",
      "jsonProp": "services",
      "type": "jsonb"
    },
    {
      "column": "spotify_url",
      "jsonProp": "spotify_url",
      "type": "text"
    },
    {
      "column": "apple_music_url",
      "jsonProp": "apple_music_url",
      "type": "text"
    },
    {
      "column": "instagram_url",
      "jsonProp": "instagram_url",
      "type": "text"
    },
    {
      "column": "twitter_url",
      "jsonProp": "twitter_url",
      "type": "text"
    },
    {
      "column": "tiktok_url",
      "jsonProp": "tiktok_url",
      "type": "text"
    },
    {
      "column": "youtube_url",
      "jsonProp": "youtube_url",
      "type": "text"
    },
    {
      "column": "facebook_url",
      "jsonProp": "facebook_url",
      "type": "text"
    },
    {
      "column": "audiomack_url",
      "jsonProp": "audiomack_url",
      "type": "text"
    },
    {
      "column": "soundcloud_url",
      "jsonProp": "soundcloud_url",
      "type": "text"
    },
    {
      "column": "boomplay_url",
      "jsonProp": "boomplay_url",
      "type": "text"
    },
    {
      "column": "deezer_url",
      "jsonProp": "deezer_url",
      "type": "text"
    },
    {
      "column": "bandcamp_url",
      "jsonProp": "bandcamp_url",
      "type": "text"
    },
    {
      "column": "mixcloud_url",
      "jsonProp": "mixcloud_url",
      "type": "text"
    },
    {
      "column": "telegram_url",
      "jsonProp": "telegram_url",
      "type": "text"
    },
    {
      "column": "threads_url",
      "jsonProp": "threads_url",
      "type": "text"
    },
    {
      "column": "snapchat_url",
      "jsonProp": "snapchat_url",
      "type": "text"
    },
    {
      "column": "linkedin_url",
      "jsonProp": "linkedin_url",
      "type": "text"
    },
    {
      "column": "twitch_url",
      "jsonProp": "twitch_url",
      "type": "text"
    },
    {
      "column": "pinterest_url",
      "jsonProp": "pinterest_url",
      "type": "text"
    },
    {
      "column": "website_url",
      "jsonProp": "website_url",
      "type": "text"
    },
    {
      "column": "avatar_url",
      "jsonProp": "avatar_url",
      "type": "text"
    },
    {
      "column": "banner_url",
      "jsonProp": "banner_url",
      "type": "text"
    },
    {
      "column": "gallery_photos",
      "jsonProp": "gallery_photos",
      "type": "jsonb"
    },
    {
      "column": "gallery_videos",
      "jsonProp": "gallery_videos",
      "type": "jsonb"
    },
    {
      "column": "verified",
      "jsonProp": "verified",
      "type": "boolean"
    },
    {
      "column": "monthly_listeners",
      "jsonProp": "monthly_listeners",
      "type": "numeric"
    },
    {
      "column": "followers",
      "jsonProp": "followers",
      "type": "numeric"
    },
    {
      "column": "total_streams",
      "jsonProp": "total_streams",
      "type": "numeric"
    },
    {
      "column": "availability_calendar",
      "jsonProp": "availability_calendar",
      "type": "text"
    },
    {
      "column": "payment_details",
      "jsonProp": "payment_details",
      "type": "text"
    }
  ]
},
  ArtistReview: {
  "name": "ArtistReview",
  "table": "artist_reviews",
  "columns": [
    {
      "column": "artist_id",
      "jsonProp": "artist_id",
      "type": "text"
    },
    {
      "column": "reviewer_name",
      "jsonProp": "reviewer_name",
      "type": "text"
    },
    {
      "column": "reviewer_type",
      "jsonProp": "reviewer_type",
      "type": "text"
    },
    {
      "column": "rating",
      "jsonProp": "rating",
      "type": "numeric"
    },
    {
      "column": "title",
      "jsonProp": "title",
      "type": "text"
    },
    {
      "column": "body",
      "jsonProp": "body",
      "type": "text"
    },
    {
      "column": "booking_type",
      "jsonProp": "booking_type",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    }
  ]
},
  AvailabilitySlot: {
  "name": "AvailabilitySlot",
  "table": "availability_slots",
  "columns": [
    {
      "column": "artist_id",
      "jsonProp": "artist_id",
      "type": "text"
    },
    {
      "column": "artist_name",
      "jsonProp": "artist_name",
      "type": "text"
    },
    {
      "column": "date",
      "jsonProp": "date",
      "type": "date"
    },
    {
      "column": "start_time",
      "jsonProp": "start_time",
      "type": "text"
    },
    {
      "column": "end_time",
      "jsonProp": "end_time",
      "type": "text"
    },
    {
      "column": "title",
      "jsonProp": "title",
      "type": "text"
    },
    {
      "column": "booking_type",
      "jsonProp": "booking_type",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    },
    {
      "column": "notes",
      "jsonProp": "notes",
      "type": "text"
    },
    {
      "column": "booked_by_booking_id",
      "jsonProp": "booked_by_booking_id",
      "type": "text"
    },
    {
      "column": "booked_by_name",
      "jsonProp": "booked_by_name",
      "type": "text"
    }
  ]
},
  Beat: {
  "name": "Beat",
  "table": "beats",
  "columns": [
    {
      "column": "title",
      "jsonProp": "title",
      "type": "text"
    },
    {
      "column": "producer",
      "jsonProp": "producer",
      "type": "text"
    },
    {
      "column": "genre",
      "jsonProp": "genre",
      "type": "text"
    },
    {
      "column": "mood",
      "jsonProp": "mood",
      "type": "text"
    },
    {
      "column": "bpm",
      "jsonProp": "bpm",
      "type": "numeric"
    },
    {
      "column": "key",
      "jsonProp": "key",
      "type": "text"
    },
    {
      "column": "description",
      "jsonProp": "description",
      "type": "text"
    },
    {
      "column": "price",
      "jsonProp": "price",
      "type": "numeric"
    },
    {
      "column": "exclusive_price",
      "jsonProp": "exclusive_price",
      "type": "numeric"
    },
    {
      "column": "license",
      "jsonProp": "license",
      "type": "text"
    },
    {
      "column": "artwork_url",
      "jsonProp": "artwork_url",
      "type": "text"
    },
    {
      "column": "tags",
      "jsonProp": "tags",
      "type": "jsonb"
    },
    {
      "column": "sales",
      "jsonProp": "sales",
      "type": "numeric"
    }
  ]
},
  Beneficiary: {
  "name": "Beneficiary",
  "table": "beneficiarys",
  "columns": [
    {
      "column": "name",
      "jsonProp": "name",
      "type": "text"
    },
    {
      "column": "nickname",
      "jsonProp": "nickname",
      "type": "text"
    },
    {
      "column": "account_number",
      "jsonProp": "account_number",
      "type": "text"
    },
    {
      "column": "bank_name",
      "jsonProp": "bank_name",
      "type": "text"
    },
    {
      "column": "bank_code",
      "jsonProp": "bank_code",
      "type": "text"
    },
    {
      "column": "currency",
      "jsonProp": "currency",
      "type": "text"
    },
    {
      "column": "country",
      "jsonProp": "country",
      "type": "text"
    },
    {
      "column": "email",
      "jsonProp": "email",
      "type": "text"
    },
    {
      "column": "type",
      "jsonProp": "type",
      "type": "text"
    }
  ]
},
  Campaign: {
  "name": "Campaign",
  "table": "campaigns",
  "columns": [
    {
      "column": "name",
      "jsonProp": "name",
      "type": "text"
    },
    {
      "column": "song",
      "jsonProp": "song",
      "type": "text"
    },
    {
      "column": "package",
      "jsonProp": "package",
      "type": "text"
    },
    {
      "column": "platform",
      "jsonProp": "platform",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    },
    {
      "column": "budget",
      "jsonProp": "budget",
      "type": "numeric"
    },
    {
      "column": "reach",
      "jsonProp": "reach",
      "type": "numeric"
    },
    {
      "column": "streams",
      "jsonProp": "streams",
      "type": "numeric"
    },
    {
      "column": "clicks",
      "jsonProp": "clicks",
      "type": "numeric"
    },
    {
      "column": "growth",
      "jsonProp": "growth",
      "type": "numeric"
    }
  ]
},
  Event: {
  "name": "Event",
  "table": "events",
  "columns": [
    {
      "column": "title",
      "jsonProp": "title",
      "type": "text"
    },
    {
      "column": "artist",
      "jsonProp": "artist",
      "type": "text"
    },
    {
      "column": "description",
      "jsonProp": "description",
      "type": "text"
    },
    {
      "column": "date",
      "jsonProp": "date",
      "type": "date"
    },
    {
      "column": "time",
      "jsonProp": "time",
      "type": "text"
    },
    {
      "column": "venue",
      "jsonProp": "venue",
      "type": "text"
    },
    {
      "column": "location",
      "jsonProp": "location",
      "type": "text"
    },
    {
      "column": "artwork_url",
      "jsonProp": "artwork_url",
      "type": "text"
    },
    {
      "column": "is_free",
      "jsonProp": "is_free",
      "type": "boolean"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    },
    {
      "column": "total_tickets",
      "jsonProp": "total_tickets",
      "type": "numeric"
    },
    {
      "column": "tickets_sold",
      "jsonProp": "tickets_sold",
      "type": "numeric"
    },
    {
      "column": "general_price",
      "jsonProp": "general_price",
      "type": "numeric"
    },
    {
      "column": "vip_price",
      "jsonProp": "vip_price",
      "type": "numeric"
    },
    {
      "column": "early_bird_price",
      "jsonProp": "early_bird_price",
      "type": "numeric"
    },
    {
      "column": "early_bird_available",
      "jsonProp": "early_bird_available",
      "type": "numeric"
    },
    {
      "column": "currency",
      "jsonProp": "currency",
      "type": "text"
    },
    {
      "column": "revenue",
      "jsonProp": "revenue",
      "type": "numeric"
    }
  ]
},
  Investment: {
  "name": "Investment",
  "table": "investments",
  "columns": [
    {
      "column": "shares",
      "jsonProp": "shares",
      "type": "numeric"
    },
    {
      "column": "price_per_share",
      "jsonProp": "price_per_share",
      "type": "numeric"
    },
    {
      "column": "amount",
      "jsonProp": "amount",
      "type": "numeric"
    },
    {
      "column": "currency",
      "jsonProp": "currency",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    }
  ]
},
  KycDocument: {
  "name": "KycDocument",
  "table": "kyc_documents",
  "columns": [
    {
      "column": "type",
      "jsonProp": "type",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    },
    {
      "column": "document_url",
      "jsonProp": "document_url",
      "type": "text"
    },
    {
      "column": "notes",
      "jsonProp": "notes",
      "type": "text"
    },
    {
      "column": "verified_at",
      "jsonProp": "verified_at",
      "type": "text"
    }
  ]
},
  Label: {
  "name": "Label",
  "table": "labels",
  "columns": [
    {
      "column": "name",
      "jsonProp": "name",
      "type": "text"
    },
    {
      "column": "description",
      "jsonProp": "description",
      "type": "text"
    },
    {
      "column": "logo_url",
      "jsonProp": "logo_url",
      "type": "text"
    },
    {
      "column": "website",
      "jsonProp": "website",
      "type": "text"
    },
    {
      "column": "country",
      "jsonProp": "country",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    },
    {
      "column": "artist_count",
      "jsonProp": "artist_count",
      "type": "numeric"
    },
    {
      "column": "total_releases",
      "jsonProp": "total_releases",
      "type": "numeric"
    },
    {
      "column": "revenue",
      "jsonProp": "revenue",
      "type": "numeric"
    }
  ]
},
  Notification: {
  "name": "Notification",
  "table": "notifications",
  "columns": [
    {
      "column": "title",
      "jsonProp": "title",
      "type": "text"
    },
    {
      "column": "message",
      "jsonProp": "message",
      "type": "text"
    },
    {
      "column": "type",
      "jsonProp": "type",
      "type": "text"
    },
    {
      "column": "category",
      "jsonProp": "category",
      "type": "text"
    },
    {
      "column": "read",
      "jsonProp": "read",
      "type": "boolean"
    },
    {
      "column": "action_url",
      "jsonProp": "action_url",
      "type": "text"
    }
  ]
},
  Order: {
  "name": "Order",
  "table": "orders",
  "columns": [
    {
      "column": "product_id",
      "jsonProp": "product_id",
      "type": "text"
    },
    {
      "column": "product_name",
      "jsonProp": "product_name",
      "type": "text"
    },
    {
      "column": "product_type",
      "jsonProp": "product_type",
      "type": "text"
    },
    {
      "column": "amount",
      "jsonProp": "amount",
      "type": "numeric"
    },
    {
      "column": "currency",
      "jsonProp": "currency",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    },
    {
      "column": "buyer_name",
      "jsonProp": "buyer_name",
      "type": "text"
    },
    {
      "column": "buyer_email",
      "jsonProp": "buyer_email",
      "type": "text"
    },
    {
      "column": "payment_method",
      "jsonProp": "payment_method",
      "type": "text"
    }
  ]
},
  Product: {
  "name": "Product",
  "table": "products",
  "columns": [
    {
      "column": "name",
      "jsonProp": "name",
      "type": "text"
    },
    {
      "column": "type",
      "jsonProp": "type",
      "type": "text"
    },
    {
      "column": "description",
      "jsonProp": "description",
      "type": "text"
    },
    {
      "column": "price",
      "jsonProp": "price",
      "type": "numeric"
    },
    {
      "column": "currency",
      "jsonProp": "currency",
      "type": "text"
    },
    {
      "column": "inventory",
      "jsonProp": "inventory",
      "type": "numeric"
    },
    {
      "column": "artwork_url",
      "jsonProp": "artwork_url",
      "type": "text"
    },
    {
      "column": "file_url",
      "jsonProp": "file_url",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    },
    {
      "column": "sales",
      "jsonProp": "sales",
      "type": "numeric"
    },
    {
      "column": "digital",
      "jsonProp": "digital",
      "type": "boolean"
    }
  ]
},
  Release: {
  "name": "Release",
  "table": "releases",
  "columns": [
    {
      "column": "title",
      "jsonProp": "title",
      "type": "text"
    },
    {
      "column": "artist",
      "jsonProp": "artist",
      "type": "text"
    },
    {
      "column": "featured_artist",
      "jsonProp": "featured_artist",
      "type": "text"
    },
    {
      "column": "genre",
      "jsonProp": "genre",
      "type": "text"
    },
    {
      "column": "language",
      "jsonProp": "language",
      "type": "text"
    },
    {
      "column": "type",
      "jsonProp": "type",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    },
    {
      "column": "release_date",
      "jsonProp": "release_date",
      "type": "date"
    },
    {
      "column": "artwork_url",
      "jsonProp": "artwork_url",
      "type": "text"
    },
    {
      "column": "audio_url",
      "jsonProp": "audio_url",
      "type": "text"
    },
    {
      "column": "royalties",
      "jsonProp": "royalties",
      "type": "numeric"
    },
    {
      "column": "streams",
      "jsonProp": "streams",
      "type": "numeric"
    },
    {
      "column": "payment_status",
      "jsonProp": "payment_status",
      "type": "text"
    },
    {
      "column": "payment_transaction_id",
      "jsonProp": "payment_transaction_id",
      "type": "text"
    },
    {
      "column": "distribution_unlocked",
      "jsonProp": "distribution_unlocked",
      "type": "boolean"
    },
    {
      "column": "territories",
      "jsonProp": "territories",
      "type": "jsonb"
    },
    {
      "column": "platforms",
      "jsonProp": "platforms",
      "type": "jsonb"
    },
    {
      "column": "content_id_status",
      "jsonProp": "content_id_status",
      "type": "text"
    },
    {
      "column": "version",
      "jsonProp": "version",
      "type": "text"
    },
    {
      "column": "metadata_valid",
      "jsonProp": "metadata_valid",
      "type": "boolean"
    },
    {
      "column": "fast_review",
      "jsonProp": "fast_review",
      "type": "boolean"
    },
    {
      "column": "distribution_attempts",
      "jsonProp": "distribution_attempts",
      "type": "numeric"
    },
    {
      "column": "last_distributed_at",
      "jsonProp": "last_distributed_at",
      "type": "text"
    },
    {
      "column": "correction_notes",
      "jsonProp": "correction_notes",
      "type": "text"
    },
    {
      "column": "takedown_status",
      "jsonProp": "takedown_status",
      "type": "text"
    },
    {
      "column": "takedown_reason",
      "jsonProp": "takedown_reason",
      "type": "text"
    }
  ]
},
  RoyaltyStatement: {
  "name": "RoyaltyStatement",
  "table": "royalty_statements",
  "columns": [
    {
      "column": "period",
      "jsonProp": "period",
      "type": "text"
    },
    {
      "column": "type",
      "jsonProp": "type",
      "type": "text"
    },
    {
      "column": "amount",
      "jsonProp": "amount",
      "type": "numeric"
    },
    {
      "column": "currency",
      "jsonProp": "currency",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    },
    {
      "column": "streams",
      "jsonProp": "streams",
      "type": "numeric"
    },
    {
      "column": "songs",
      "jsonProp": "songs",
      "type": "numeric"
    },
    {
      "column": "artist_share",
      "jsonProp": "artist_share",
      "type": "numeric"
    },
    {
      "column": "producer_share",
      "jsonProp": "producer_share",
      "type": "numeric"
    },
    {
      "column": "xedruo_share",
      "jsonProp": "xedruo_share",
      "type": "numeric"
    }
  ]
},
  Song: {
  "name": "Song",
  "table": "songs",
  "columns": [
    {
      "column": "title",
      "jsonProp": "title",
      "type": "text"
    },
    {
      "column": "artist",
      "jsonProp": "artist",
      "type": "text"
    },
    {
      "column": "composers",
      "jsonProp": "composers",
      "type": "jsonb"
    },
    {
      "column": "lyricists",
      "jsonProp": "lyricists",
      "type": "jsonb"
    },
    {
      "column": "publishers",
      "jsonProp": "publishers",
      "type": "jsonb"
    },
    {
      "column": "isrc",
      "jsonProp": "isrc",
      "type": "text"
    },
    {
      "column": "iswc",
      "jsonProp": "iswc",
      "type": "text"
    },
    {
      "column": "upc",
      "jsonProp": "upc",
      "type": "text"
    },
    {
      "column": "genre",
      "jsonProp": "genre",
      "type": "text"
    },
    {
      "column": "language",
      "jsonProp": "language",
      "type": "text"
    },
    {
      "column": "duration",
      "jsonProp": "duration",
      "type": "numeric"
    },
    {
      "column": "release_date",
      "jsonProp": "release_date",
      "type": "date"
    },
    {
      "column": "splits",
      "jsonProp": "splits",
      "type": "jsonb"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    },
    {
      "column": "sync_available",
      "jsonProp": "sync_available",
      "type": "boolean"
    },
    {
      "column": "content_id",
      "jsonProp": "content_id",
      "type": "boolean"
    }
  ]
},
  StudioBooking: {
  "name": "StudioBooking",
  "table": "studio_bookings",
  "columns": [
    {
      "column": "service",
      "jsonProp": "service",
      "type": "text"
    },
    {
      "column": "name",
      "jsonProp": "name",
      "type": "text"
    },
    {
      "column": "email",
      "jsonProp": "email",
      "type": "text"
    },
    {
      "column": "phone",
      "jsonProp": "phone",
      "type": "text"
    },
    {
      "column": "date",
      "jsonProp": "date",
      "type": "text"
    },
    {
      "column": "notes",
      "jsonProp": "notes",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    }
  ]
},
  SupportTicket: {
  "name": "SupportTicket",
  "table": "support_tickets",
  "columns": [
    {
      "column": "title",
      "jsonProp": "title",
      "type": "text"
    },
    {
      "column": "description",
      "jsonProp": "description",
      "type": "text"
    },
    {
      "column": "category",
      "jsonProp": "category",
      "type": "text"
    },
    {
      "column": "priority",
      "jsonProp": "priority",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    },
    {
      "column": "response",
      "jsonProp": "response",
      "type": "text"
    },
    {
      "column": "user_email",
      "jsonProp": "user_email",
      "type": "text"
    }
  ]
},
  TicketPurchase: {
  "name": "TicketPurchase",
  "table": "ticket_purchases",
  "columns": [
    {
      "column": "event_id",
      "jsonProp": "event_id",
      "type": "text"
    },
    {
      "column": "event_title",
      "jsonProp": "event_title",
      "type": "text"
    },
    {
      "column": "event_date",
      "jsonProp": "event_date",
      "type": "text"
    },
    {
      "column": "venue",
      "jsonProp": "venue",
      "type": "text"
    },
    {
      "column": "ticket_type",
      "jsonProp": "ticket_type",
      "type": "text"
    },
    {
      "column": "quantity",
      "jsonProp": "quantity",
      "type": "numeric"
    },
    {
      "column": "amount_paid",
      "jsonProp": "amount_paid",
      "type": "numeric"
    },
    {
      "column": "currency",
      "jsonProp": "currency",
      "type": "text"
    },
    {
      "column": "buyer_name",
      "jsonProp": "buyer_name",
      "type": "text"
    },
    {
      "column": "buyer_email",
      "jsonProp": "buyer_email",
      "type": "text"
    },
    {
      "column": "buyer_phone",
      "jsonProp": "buyer_phone",
      "type": "text"
    },
    {
      "column": "payment_status",
      "jsonProp": "payment_status",
      "type": "text"
    },
    {
      "column": "qr_code",
      "jsonProp": "qr_code",
      "type": "text"
    },
    {
      "column": "ticket_number",
      "jsonProp": "ticket_number",
      "type": "text"
    },
    {
      "column": "artist_share",
      "jsonProp": "artist_share",
      "type": "numeric"
    },
    {
      "column": "producer_share",
      "jsonProp": "producer_share",
      "type": "numeric"
    },
    {
      "column": "xedruo_share",
      "jsonProp": "xedruo_share",
      "type": "numeric"
    }
  ]
},
  User: {
  "name": "User",
  "table": "user_profiles",
  "columns": [
    {
      "column": "role",
      "jsonProp": "role",
      "type": "text"
    }
  ]
},
  WalletTransaction: {
  "name": "WalletTransaction",
  "table": "wallet_transactions",
  "columns": [
    {
      "column": "description",
      "jsonProp": "description",
      "type": "text"
    },
    {
      "column": "type",
      "jsonProp": "type",
      "type": "text"
    },
    {
      "column": "amount",
      "jsonProp": "amount",
      "type": "numeric"
    },
    {
      "column": "currency",
      "jsonProp": "currency",
      "type": "text"
    },
    {
      "column": "category",
      "jsonProp": "category",
      "type": "text"
    },
    {
      "column": "status",
      "jsonProp": "status",
      "type": "text"
    },
    {
      "column": "artist_share",
      "jsonProp": "artist_share",
      "type": "numeric"
    },
    {
      "column": "producer_share",
      "jsonProp": "producer_share",
      "type": "numeric"
    },
    {
      "column": "xedruo_share",
      "jsonProp": "xedruo_share",
      "type": "numeric"
    },
    {
      "column": "linked_release_id",
      "jsonProp": "linked_release_id",
      "type": "text"
    },
    {
      "column": "linked_event_id",
      "jsonProp": "linked_event_id",
      "type": "text"
    }
  ]
},
};
